@testset "Backend switching" begin
    if TEST_BACKEND == NVIDIABackend()
        @test GPUInspector.is_cuda_loaded()
        @test GPUInspector.is_backend_loaded(NVIDIABackend())
        @test backend() == NVIDIABackend()
        @test isnothing(backend!(NoBackend()))
        @test backend() == NoBackend()
        @test isnothing(backend!(:cuda))
        @test backend() == NVIDIABackend()
        @test isnothing(backend!(NVIDIABackend()))
    elseif TEST_BACKEND == AMDBackend()
        @test GPUInspector.is_amdgpu_loaded()
        @test GPUInspector.is_backend_loaded(AMDBackend())
        @test backend() == AMDBackend()
        @test isnothing(backend!(NoBackend()))
        @test backend() == NoBackend()
        @test isnothing(backend!(:amd))
        @test backend() == AMDBackend()
        @test isnothing(backend!(AMDBackend()))
    end
end
